### ISSUE TITLE
Tainted Canvas Issue

### ISSUE THREAD

**Issue by sean-olson** [WSDOT-GIS/arcgis-map-thumbnail-builder#8]
Hi, first let me say, very nice library.  We implemented this in our app.  Ran it locally, and it works fine.  Deployed the app to an AWS box using Docker and it throws an error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.  I thought you or someone else might have experienced this before.  Cheers!

**Comment by JeffJacobson** [comment]
I haven't used Docker or AWS before.

Do you experience the same issues from the [demo app on GitHub pages](http://wsdot-gis.github.io/arcgis-map-thumbnail-builder/)?

**Comment by sean-olson** [comment]
Really slow response on my part, Jeff --sorry about that.  This turns out to be a know security "feature" for the Canvas element.  It's basically CORS for the UI.  We resolved it by using Leaflet.  Thanks again.
